# permissions for end users to edit registers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: register-editor-role
rules:
- apiGroups:
  - vault.cattle.io
  resources:
  - registers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.cattle.io
  resources:
  - registers/status
  verbs:
  - get
